// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.hsqldb.jdbcDriver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.yumka.leman.database;

import java.util.Comparator;

// imports+

// imports-

/**
 * Comparator class is used to sort the EvaluationsBean objects.
 */
public class EvaluationsComparator implements Comparator
// extends+

// extends-
{
  /**
   * Holds the field on which the comparison is performed.
   */
  private int iType;

  /**
   * Value that will contain the information about the order of the sort: normal or reversal.
   */
  private boolean bReverse;

  /**
   * Constructor class for EvaluationsComparator.
   * <br>
   * Example:
   * <br>
   * <code>Arrays.sort(pArray, new EvaluationsComparator(EvaluationsManager.ID, bReverse));<code>
   *
   * @param iType the field from which you want to sort
   * <br>
   * Possible values are:
   * <ul>
   *   <li>EvaluationsManager.ID_ID
   *   <li>EvaluationsManager.ID_IDORGANIZATION
   *   <li>EvaluationsManager.ID_IDUSER
   *   <li>EvaluationsManager.ID_DATE
   *   <li>EvaluationsManager.ID_TIME
   *   <li>EvaluationsManager.ID_ORGANIZATION
   * </ul>
   */
  public EvaluationsComparator(int iType) {
    this(iType, false);
  }

  /**
   * Constructor class for EvaluationsComparator.
   * <br>
   * Example:
   * <br>
   * <code>Arrays.sort(pArray, new EvaluationsComparator(EvaluationsManager.ID, bReverse));<code>
   *
   * @param iType the field from which you want to sort.
   * <br>
   * Possible values are:
   * <ul>
   *   <li>EvaluationsManager.ID_ID
   *   <li>EvaluationsManager.ID_IDORGANIZATION
   *   <li>EvaluationsManager.ID_IDUSER
   *   <li>EvaluationsManager.ID_DATE
   *   <li>EvaluationsManager.ID_TIME
   *   <li>EvaluationsManager.ID_ORGANIZATION
   * </ul>
   *
   * @param bReverse set this value to true, if you want to reverse the sorting results
   */
  public EvaluationsComparator(int iType, boolean bReverse) {
    this.iType = iType;
    this.bReverse = bReverse;
  }

  /**
   * Implementation of the compare method.
   */
  public int compare(Object pObj1, Object pObj2) {
    EvaluationsBean b1 = (EvaluationsBean) pObj1;
    EvaluationsBean b2 = (EvaluationsBean) pObj2;
    int iReturn = 0;
    switch (iType) {
      case EvaluationsManager.ID_ID:
        if (b1.getId() == null && b2.getId() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getId() == null && b2.getId() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getId() != null && b2.getId() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getId().compareTo(b2.getId());
            }
          }
        }
        break;
      case EvaluationsManager.ID_IDORGANIZATION:
        if (b1.getIdorganization() == null && b2.getIdorganization() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getIdorganization() == null && b2.getIdorganization() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getIdorganization() != null && b2.getIdorganization() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getIdorganization().compareTo(b2.getIdorganization());
            }
          }
        }
        break;
      case EvaluationsManager.ID_IDUSER:
        if (b1.getIduser() == null && b2.getIduser() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getIduser() == null && b2.getIduser() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getIduser() != null && b2.getIduser() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getIduser().compareTo(b2.getIduser());
            }
          }
        }
        break;
      case EvaluationsManager.ID_DATE:
        if (b1.getDate() == null && b2.getDate() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getDate() == null && b2.getDate() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getDate() != null && b2.getDate() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getDate().compareTo(b2.getDate());
            }
          }
        }
        break;
      case EvaluationsManager.ID_TIME:
        if (b1.getTime() == null && b2.getTime() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getTime() == null && b2.getTime() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getTime() != null && b2.getTime() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getTime().compareTo(b2.getTime());
            }
          }
        }
        break;
      case EvaluationsManager.ID_ORGANIZATION:
        if (b1.getOrganization() == null && b2.getOrganization() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getOrganization() == null && b2.getOrganization() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getOrganization() != null && b2.getOrganization() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getOrganization().compareTo(b2.getOrganization());
            }
          }
        }
        break;
      default:
        throw new IllegalArgumentException(
            "Type passed for the field is not supported");
    }

    return bReverse ? ( -1 * iReturn) : iReturn;
  }

// class+

// class-
}
