// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.hsqldb.jdbcDriver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.yumka.leman.database;

import java.sql.SQLException;

// imports+

// imports-


/**
 * Listener that is notified of EVALUATIONS table changes.
 */
public interface EvaluationsListener
// extends+

// extends-
{
  /**
   * Invoked just before inserting a EvaluationsBean record into the database.
   *
   * @param pObject the EvaluationsBean that is about to be inserted
   */
  public void beforeInsert(EvaluationsBean pObject) throws SQLException;

  /**
   * Invoked just after a EvaluationsBean record is inserted in the database.
   *
   * @param pObject the EvaluationsBean that was just inserted
   */
  public void afterInsert(EvaluationsBean pObject) throws SQLException;

  /**
   * Invoked just before updating a EvaluationsBean record in the database.
   *
   * @param pObject the EvaluationsBean that is about to be updated
   */
  public void beforeUpdate(EvaluationsBean pObject) throws SQLException;

  /**
   * Invoked just after updating a EvaluationsBean record in the database.
   *
   * @param pObject the EvaluationsBean that was just updated
   */
  public void afterUpdate(EvaluationsBean pObject) throws SQLException;

// class+

// class-
}
