// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.hsqldb.jdbcDriver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.yumka.leman.database;

import java.util.Comparator;

// imports+

// imports-

/**
 * Comparator class is used to sort the EvaluationsdetailBean objects.
 */
public class EvaluationsdetailComparator implements Comparator
// extends+

// extends-
{
  /**
   * Holds the field on which the comparison is performed.
   */
  private int iType;

  /**
   * Value that will contain the information about the order of the sort: normal or reversal.
   */
  private boolean bReverse;

  /**
   * Constructor class for EvaluationsdetailComparator.
   * <br>
   * Example:
   * <br>
   * <code>Arrays.sort(pArray, new EvaluationsdetailComparator(EvaluationsdetailManager.ID, bReverse));<code>
   *
   * @param iType the field from which you want to sort
   * <br>
   * Possible values are:
   * <ul>
   *   <li>EvaluationsdetailManager.ID_ID
   *   <li>EvaluationsdetailManager.ID_IDEVALUATION
   *   <li>EvaluationsdetailManager.ID_IDQUESTION
   *   <li>EvaluationsdetailManager.ID_IDRESPONSE
   * </ul>
   */
  public EvaluationsdetailComparator(int iType) {
    this(iType, false);
  }

  /**
   * Constructor class for EvaluationsdetailComparator.
   * <br>
   * Example:
   * <br>
   * <code>Arrays.sort(pArray, new EvaluationsdetailComparator(EvaluationsdetailManager.ID, bReverse));<code>
   *
   * @param iType the field from which you want to sort.
   * <br>
   * Possible values are:
   * <ul>
   *   <li>EvaluationsdetailManager.ID_ID
   *   <li>EvaluationsdetailManager.ID_IDEVALUATION
   *   <li>EvaluationsdetailManager.ID_IDQUESTION
   *   <li>EvaluationsdetailManager.ID_IDRESPONSE
   * </ul>
   *
   * @param bReverse set this value to true, if you want to reverse the sorting results
   */
  public EvaluationsdetailComparator(int iType, boolean bReverse) {
    this.iType = iType;
    this.bReverse = bReverse;
  }

  /**
   * Implementation of the compare method.
   */
  public int compare(Object pObj1, Object pObj2) {
    EvaluationsdetailBean b1 = (EvaluationsdetailBean) pObj1;
    EvaluationsdetailBean b2 = (EvaluationsdetailBean) pObj2;
    int iReturn = 0;
    switch (iType) {
      case EvaluationsdetailManager.ID_ID:
        if (b1.getId() == null && b2.getId() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getId() == null && b2.getId() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getId() != null && b2.getId() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getId().compareTo(b2.getId());
            }
          }
        }
        break;
      case EvaluationsdetailManager.ID_IDEVALUATION:
        if (b1.getIdevaluation() == null && b2.getIdevaluation() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getIdevaluation() == null && b2.getIdevaluation() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getIdevaluation() != null && b2.getIdevaluation() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getIdevaluation().compareTo(b2.getIdevaluation());
            }
          }
        }
        break;
      case EvaluationsdetailManager.ID_IDQUESTION:
        if (b1.getIdquestion() == null && b2.getIdquestion() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getIdquestion() == null && b2.getIdquestion() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getIdquestion() != null && b2.getIdquestion() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getIdquestion().compareTo(b2.getIdquestion());
            }
          }
        }
        break;
      case EvaluationsdetailManager.ID_IDRESPONSE:
        if (b1.getIdresponse() == null && b2.getIdresponse() != null) {
          iReturn = -1;
        }
        else {
          if (b1.getIdresponse() == null && b2.getIdresponse() == null) {
            iReturn = 0;
          }
          else {
            if (b1.getIdresponse() != null && b2.getIdresponse() == null) {
              iReturn = 1;
            }
            else {
              iReturn = b1.getIdresponse().compareTo(b2.getIdresponse());
            }
          }
        }
        break;
      default:
        throw new IllegalArgumentException(
            "Type passed for the field is not supported");
    }

    return bReverse ? ( -1 * iReturn) : iReturn;
  }

// class+

// class-
}
