// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.hsqldb.jdbcDriver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.yumka.leman.database;

import java.sql.*;
// imports+ 

// imports- 


/**
 * Listener that is notified of OBSERVATIONS table changes.
 */
public interface ObservationsListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a ObservationsBean record into the database.
     *
     * @param pObject the ObservationsBean that is about to be inserted
     */
    public void beforeInsert(ObservationsBean pObject) throws SQLException;


    /**
     * Invoked just after a ObservationsBean record is inserted in the database.
     *
     * @param pObject the ObservationsBean that was just inserted
     */
    public void afterInsert(ObservationsBean pObject) throws SQLException;


    /**
     * Invoked just before updating a ObservationsBean record in the database.
     *
     * @param pObject the ObservationsBean that is about to be updated
     */
    public void beforeUpdate(ObservationsBean pObject) throws SQLException;


    /**
     * Invoked just after updating a ObservationsBean record in the database.
     *
     * @param pObject the ObservationsBean that was just updated
     */
    public void afterUpdate(ObservationsBean pObject) throws SQLException;


// class+ 

// class- 
}
