// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.hsqldb.jdbcDriver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.yumka.leman.database;

import java.sql.SQLException;

// imports+

// imports-


/**
 * Listener that is notified of ORGANIZATIONS table changes.
 */
public interface OrganizationsListener
// extends+

// extends-
{
  /**
   * Invoked just before inserting a OrganizationsBean record into the database.
   *
   * @param pObject the OrganizationsBean that is about to be inserted
   */
  public void beforeInsert(OrganizationBean pObject) throws SQLException;

  /**
   * Invoked just after a OrganizationsBean record is inserted in the database.
   *
   * @param pObject the OrganizationsBean that was just inserted
   */
  public void afterInsert(OrganizationBean pObject) throws SQLException;

  /**
   * Invoked just before updating a OrganizationsBean record in the database.
   *
   * @param pObject the OrganizationsBean that is about to be updated
   */
  public void beforeUpdate(OrganizationBean pObject) throws SQLException;

  /**
   * Invoked just after updating a OrganizationsBean record in the database.
   *
   * @param pObject the OrganizationsBean that was just updated
   */
  public void afterUpdate(OrganizationBean pObject) throws SQLException;

// class+

// class-
}
