// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.hsqldb.jdbcDriver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.yumka.leman.database;

import java.sql.SQLException;

// imports+

// imports-


/**
 * Listener that is notified of QUESTIONS table changes.
 */
public interface QuestionsListener
// extends+

// extends-
{
  /**
   * Invoked just before inserting a QuestionsBean record into the database.
   *
   * @param pObject the QuestionsBean that is about to be inserted
   */
  public void beforeInsert(QuestionsBean pObject) throws SQLException;

  /**
   * Invoked just after a QuestionsBean record is inserted in the database.
   *
   * @param pObject the QuestionsBean that was just inserted
   */
  public void afterInsert(QuestionsBean pObject) throws SQLException;

  /**
   * Invoked just before updating a QuestionsBean record in the database.
   *
   * @param pObject the QuestionsBean that is about to be updated
   */
  public void beforeUpdate(QuestionsBean pObject) throws SQLException;

  /**
   * Invoked just after updating a QuestionsBean record in the database.
   *
   * @param pObject the QuestionsBean that was just updated
   */
  public void afterUpdate(QuestionsBean pObject) throws SQLException;

// class+

// class-
}
